import http from 'k6/http'
import { check, sleep } from 'k6'
import { Rate, Trend } from 'k6/metrics'

const baseUrl = __ENV.API_URL || 'http://localhost:4000'
const token = __ENV.TOKEN

const ticketTrend = new Trend('ticket_list_duration')
const ticketErrors = new Rate('ticket_errors')

export const options = {
  stages: [
    { duration: '30s', target: 20 },
    { duration: '1m', target: 100 },
    { duration: '30s', target: 200 },
    { duration: '1m', target: 200 },
    { duration: '30s', target: 0 },
  ],
  thresholds: {
    ticket_errors: ['rate<0.01'],
    http_req_duration: ['p(95)<1000'],
  },
}

const headers = {
  headers: { Authorization: `Bearer ${token}` },
}

export default function () {
  const listRes = http.get(`${baseUrl}/api/tickets?page=1&limit=20`, headers)
  ticketTrend.add(listRes.timings.duration)
  ticketErrors.add(listRes.status !== 200)

  check(listRes, {
    'tickets list status 200': (r) => r.status === 200,
    'tickets has data': (r) => Array.isArray(r.json('data')),
  })

  const payload = JSON.stringify({
    title: `Load test ticket ${Date.now()}`,
    description: 'Generated by k6 load test',
    priority: 'low',
    category: 'support',
  })
  const createRes = http.post(`${baseUrl}/api/tickets`, payload, {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
      'Idempotency-Key': `${__VU}-${Date.now()}`,
    },
  })
  ticketErrors.add(createRes.status !== 201)

  check(createRes, {
    'ticket created status 201': (r) => r.status === 201,
  })

  sleep(1)
}
